include ./Catppuccin-Mocha.conf

background_opacity 0.9
background_blur 10
dynamic_background_opacity yes

font_size 16.0
font_family jetBrainsMono Nerd Font
disable_ligatures never

cursor_shape beam

detect_urls yes
show_hyperlink_targets yes

copy_on_select yes

tab_bar_style powerline
tab_powerline_style slanted

linux_display_server wayland

editor nvim

# map ctrl+\ new_window
map ctrl+\ launch --cwd=current
map control+t new_tab_with_cwd
map control+] next_tab
map control+[ previous_tab
map ctrl+shift+r start_resizing_window
