icons-enabled=yes
icon-theme=Papirus
prompt="> "
password-character=*
fuzzy=yes
lines=7
width=55
line-height=30
terminal=kitty

[border]
width=2
radius=10

# catppuccin mocha
[colors]
background=1e1e2edd
text=cdd6f4ff
match=f38ba8ff
selection=585b70ff
selection-match=f38ba8ff
selection-text=cdd6f4ff
border=b4befeff
