alias icat="imgcat"
alias btm="btm --battery"
alias dwn="aria2c"
alias ff="fastfetch"
alias serve="miniserve"
alias cls="clear"
alias please="sudo"
alias ls="eza -lhaGF --icons=always --color=always --git --no-user --time-style=relative"
alias lst="eza -la -F --icons -h --color=always --git -T"
alias lsd="lsd -A --color=always --icon=always --icon-theme=fancy --header --permission=rwx --date=relative -F -l"
alias ping="gping"
alias du="dust"
alias df="duf"
alias ps="procs"
alias cat="bat"

alias save="source ~/.config/fish/config.fish"
alias fishconfig="$EDITOR ~/.config/fish/config.fish"
alias fishalias="$EDITOR ~/.config/fish/alias.fish"
alias fishfnc="$EDITOR ~/.config/fish/cust_functions.fish"
alias starship_config="$EDITOR ~/.config/starship.toml"
