alias icat="imgcat"
alias btm="btm --battery"
alias dwn="aria2c"
alias ff="fastfetch"
alias serve="miniserve"
alias agg="agg --font-dir '/home/sumanth0x637/.fonts/j' --font-family 'JetBrainsMono NF' --fps-cap 120 --font-size 16"
alias jnb="jupyter notebook --no-browser"
alias jlnb="jupyter-lab --no-browser"
alias cls="clear"
alias fishconfig="$EDITOR ~/.config/fish/config.fish"
alias fishalias="$EDITOR ~/.config/fish/alias.fish"
alias fishfnc="$EDITOR ~/.config/fish/cust_functions.fish"
alias please="sudo"
alias starship_config="$EDITOR ~/.config/starship.toml"
alias ls="eza -la -F --icons -h --color=always --git -G"
alias lst="eza -la -F --icons -h --color=always --git -T"
alias lsd="lsd -A --color=always --icon=always --icon-theme=fancy --header --permission=rwx --date=relative -F -l"
alias ping="gping"
alias du="dust"
alias df="duf"
alias ps="procs"
alias cat="bat"
alias save="source ~/.config/fish/config.fish"
