name: Fish Format Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: fish-actions/install-fish@v1

      - uses: fish-actions/format-check@v1
